#!/bin/bash
# Claw Customer Service - Interactive Setup Script
# This script guides non-technical users through configuration

set -e

echo "=========================================="
echo "🦁 Claw Customer Service Setup"
echo "=========================================="
echo ""

# Check dependencies
check_dependency() {
  if ! command -v $1 &> /dev/null; then
    echo "❌ $1 is not installed. Please install it first."
    exit 1
  fi
}

# For Docker setup
if command -v docker &> /dev/null && command -v docker-compose &> /dev/null; then
  echo "✅ Docker is installed"
  SETUP_MODE="docker"
else
  echo "⚠️  Docker not found. Install Docker Desktop or Docker Engine to continue."
  echo "   Visit: https://docs.docker.com/get-docker/"
  exit 1
fi

# Create .env file
if [ -f ".env" ]; then
  echo "⚠️  .env file already exists. Backing up to .env.bak"
  cp .env .env.bak
fi

echo ""
echo "Let's configure Claw Customer Service..."
echo ""

# Google OAuth Setup
echo "📧 GOOGLE OAUTH CONFIGURATION"
echo "================================"
echo ""
echo "You'll need a Google OAuth application. Follow these steps:"
echo "1. Go to: https://console.cloud.google.com/"
echo "2. Create a new project (or select existing)"
echo "3. Enable Gmail API and Google Sheets API"
echo "4. Create OAuth 2.0 credentials (Desktop application)"
echo "5. Download the JSON credentials file"
echo ""

read -p "Enter your Google Client ID: " GOOGLE_CLIENT_ID
read -p "Enter your Google Client Secret: " GOOGLE_CLIENT_SECRET
read -p "Enter your Google Redirect URL (default: http://localhost:3000/auth/callback): " GOOGLE_REDIRECT_URL
GOOGLE_REDIRECT_URL=${GOOGLE_REDIRECT_URL:-http://localhost:3000/auth/callback}
read -p "Paste your GOOGLE_OAUTH_TOKEN (JSON): " GOOGLE_OAUTH_TOKEN
read -p "Enter your Google Sheet ID (for knowledge base): " GOOGLE_SHEET_ID

# Twilio Setup (Optional but recommended)
echo ""
echo "📞 TWILIO PHONE CONFIGURATION (Optional)"
echo "========================================"
read -p "Do you want to enable phone support? (y/n): " ENABLE_PHONE

if [ "$ENABLE_PHONE" = "y" ] || [ "$ENABLE_PHONE" = "Y" ]; then
  echo ""
  echo "Visit https://www.twilio.com/ to set up a Twilio account"
  echo ""
  read -p "Enter your Twilio Account SID: " TWILIO_ACCOUNT_SID
  read -p "Enter your Twilio Auth Token: " TWILIO_AUTH_TOKEN
  read -p "Enter your Twilio Phone Number (e.g., +1234567890): " TWILIO_PHONE_NUMBER
  ENABLE_PHONE_FLAG=true
else
  ENABLE_PHONE_FLAG=false
fi

# LLM Configuration
echo ""
echo "🤖 LLM CONFIGURATION"
echo "===================="
echo ""
echo "Choose your primary LLM provider:"
echo "1. Ollama (Local, privacy-first, no API key needed)"
echo "2. OpenAI (GPT-3.5, GPT-4)"
echo "3. Anthropic Claude (Claude Sonnet, Opus)"
echo ""

read -p "Enter your choice (1-3, default is 1 for Ollama): " LLM_CHOICE
LLM_CHOICE=${LLM_CHOICE:-1}

case $LLM_CHOICE in
  1)
    LLM_PRIMARY_PROVIDER="ollama"
    LLM_PRIMARY_MODEL="llama2"
    LLM_PRIMARY_BASE_URL="http://ollama:11434"
    ;;
  2)
    LLM_PRIMARY_PROVIDER="openai"
    read -p "Enter your OpenAI API Key (sk-...): " LLM_FALLBACK_API_KEY
    LLM_PRIMARY_MODEL="gpt-3.5-turbo"
    ;;
  3)
    LLM_PRIMARY_PROVIDER="claude"
    read -p "Enter your Anthropic API Key (sk-ant-...): " LLM_FALLBACK_API_KEY
    LLM_PRIMARY_MODEL="claude-3-sonnet-20240229"
    ;;
esac

# Fallback LLM (optional)
echo ""
read -p "Do you want to set up a fallback LLM? (y/n): " SETUP_FALLBACK

if [ "$SETUP_FALLBACK" = "y" ] || [ "$SETUP_FALLBACK" = "Y" ]; then
  echo ""
  echo "Choose fallback provider (should be different from primary):"
  echo "1. OpenAI"
  echo "2. Anthropic Claude"
  echo ""
  read -p "Enter your choice (1-2): " FALLBACK_CHOICE
  
  if [ "$FALLBACK_CHOICE" = "1" ]; then
    LLM_FALLBACK_PROVIDER="openai"
    read -p "Enter OpenAI API Key: " LLM_FALLBACK_API_KEY
    LLM_FALLBACK_MODEL="gpt-3.5-turbo"
  elif [ "$FALLBACK_CHOICE" = "2" ]; then
    LLM_FALLBACK_PROVIDER="claude"
    read -p "Enter Anthropic API Key: " LLM_FALLBACK_API_KEY
    LLM_FALLBACK_MODEL="claude-3-sonnet-20240229"
  fi
fi

# Server Configuration
echo ""
echo "🌐 SERVER CONFIGURATION"
echo "======================="
read -p "Enter port number (default: 3000): " PORT
PORT=${PORT:-3000}

# Generate .env file
cat > .env << EOF
# Claw Customer Service Configuration
# Generated by setup.sh on $(date)

PORT=$PORT
NODE_ENV=production

# Google OAuth & APIs
GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
GOOGLE_REDIRECT_URL=$GOOGLE_REDIRECT_URL
GOOGLE_OAUTH_TOKEN=$GOOGLE_OAUTH_TOKEN
GOOGLE_SHEET_ID=$GOOGLE_SHEET_ID

# Twilio
ENABLE_PHONE=$ENABLE_PHONE_FLAG
TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID:-}
TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN:-}
TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER:-}

# LLM Configuration
LLM_PRIMARY_PROVIDER=$LLM_PRIMARY_PROVIDER
LLM_PRIMARY_MODEL=$LLM_PRIMARY_MODEL
LLM_PRIMARY_BASE_URL=${LLM_PRIMARY_BASE_URL:-}
LLM_FALLBACK_PROVIDER=${LLM_FALLBACK_PROVIDER:-}
LLM_FALLBACK_MODEL=${LLM_FALLBACK_MODEL:-}
LLM_FALLBACK_API_KEY=${LLM_FALLBACK_API_KEY:-}

# Features
ENABLE_EMAIL=true

# Logging
LOG_LEVEL=info
EOF

echo ""
echo "✅ Configuration saved to .env"
echo ""
echo "=========================================="
echo "🚀 READY TO START"
echo "=========================================="
echo ""
echo "To start Claw Customer Service:"
echo ""
echo "  docker-compose up -d"
echo ""
echo "To view logs:"
echo ""
echo "  docker-compose logs -f claw"
echo ""
echo "Access the service at:"
echo ""
echo "  http://localhost:$PORT/health"
echo ""
echo "Documentation: ./docs/SETUP.md"
echo ""
